# Generated by Django 4.0.3 on 2022-04-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_rename_todolist_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='token_manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField()),
                ('t_amount', models.IntegerField()),
            ],
        ),
    ]
