# Generated by Django 4.0.3 on 2022-04-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_token_manage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='token_manage',
            new_name='T_List',
        ),
        migrations.RenameField(
            model_name='t_list',
            old_name='t_amount',
            new_name='t_amt',
        ),
    ]
