# Generated by Django 4.0.3 on 2022-04-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_rename_token_manage_t_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='crypto_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_price', models.IntegerField()),
                ('b_amt', models.IntegerField()),
                ('b_token', models.IntegerField()),
                ('b_name', models.CharField(max_length=200)),
                ('u_id', models.IntegerField()),
            ],
        ),
    ]
