# Generated by Django 4.0.3 on 2022-04-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0006_alter_crypto_tbl_b_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto_tbl',
            name='b_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crypto_tbl',
            name='b_token',
            field=models.FloatField(),
        ),
    ]
