# Generated by Django 4.0.3 on 2022-04-06 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0007_alter_crypto_tbl_b_price_alter_crypto_tbl_b_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto_tbl',
            name='b_img',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
