# Generated by Django 4.0 on 2023-04-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0011_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Quantity',
            field=models.IntegerField(default=1, max_length=10),
        ),
    ]
